---
abstract: 'a perl implementation of Literature Based Discovery'
author:
  - 'Sam Henry <henryst@vcu.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: assocLBD
no_index:
  directory:
    - t
    - inc
requires:
  UMLS::Association: 0
  UMLS::Interface: 0
version: 0.01
